### ISSUE TITLE
Artifacting when using OpenGL / Vulkan using the nee drivers

### ISSUE THREAD

**Issue by kquote03** [Ps3itaTeam/ps4linux-video-drivers#10]
![Screenshot_2021-04-21_17-03-58](https://user-images.githubusercontent.com/37013292/116552983-b36d8b80-a90a-11eb-9279-8667267720ca.png)

It doesn't seem to affect all applications, for me both dolphin and the whole plasma desktop had this pattern of artifacts

**Comment by Ps3itaTeam** [comment]
I have always tested dolphin and i don't have any sort of artifact, probably you messed up something in the install of drivers or you are using a old kernel with a wrong rev id

Look here: https://twitter.com/Ps3ita_Team/status/1266028689252323330?s=19
