### ISSUE TITLE
Sata controller don't work [FAT/SLIM/PRO]

### ISSUE THREAD

**Issue by Tikilou** [Ps3itaTeam/ps4linux-video-drivers#2]
Hi, it's appears in ahci.c you have added support for Belize Controller, and Marcan on Fail0verflow was added Aeolia support. Unfortunatly, it's actually not working, we can't see hard drive. Any idea ?

**Comment by mirh** [comment]
Fixed as per https://github.com/Ps3itaTeam/ps4-linux/commit/7ff7d8510c17d2506f87c49da027130102964e87
