### ISSUE TITLE
error PKGBUILD mesa

### ISSUE THREAD

**Issue by gamernewone** [Ps3itaTeam/ps4linux-video-drivers#6]
[psxita@psxitarch lib32-mesa-git]$ makepkg
==> Création du paquet lib32-mesa-git 19.0.0_devel.106770.b938d5fbef-1 (ven. 16 août 2019 03:02:00 CEST)
==> Vérification des dépendances pour l’exécution…
==> Vérification des dépendances pour la compilation…
==> Récupération des sources…
  -> Clonage du dépôt mesa git…
Clonage dans le dépôt nu '/home/psxita/Downloads/ps4linux-video-drivers/lib32-mesa-git/mesa'
remote: Counting objects: 1115686, done.
remote: Compressing objects: 100% (161260/161260), done.
remote: Total 1115686 (delta 953689), reused 1110473 (delta 949038)
Réception d'objets: 100% (1115686/1115686), 198.57 MiB | 71.00 KiB/s, fait.
Résolution des deltas: 100% (953689/953689), fait.
  -> LICENSE trouvé
  -> llvm32.native trouvé
==> Validation des fichiers source avec sha512sums…
    mesa ... Ignoré
    LICENSE ... Réussite
    llvm32.native ... Réussite
==> Extraction des sources…
  -> Création d’une copie de travail du dépot mesa git…
Clonage dans 'mesa'...
fait.
Extraction des fichiers: 100% (7036/7036), fait.
==> Lancement de prepare()…
1 out of 1 hunk FAILED -- saving rejects to file mesa/src/amd/common/ac_surface.c.rej
2 out of 4 hunks FAILED -- saving rejects to file mesa/src/gallium/winsys/radeon/drm/radeon_drm_winsys.c.rej
==> ERREUR : Une erreur s’est produite dans prepare().
    Abandon…
[psxita@psxitarch lib32-mesa-git]$ sudo pacman -S lib32-libva

**Comment by mirh** [comment]
https://github.com/mesa3d/mesa/commit/0032f6b8a0f9d1c8082ea795464010fbb687ab4c
https://github.com/mesa3d/mesa/commit/b25795602160af020d6bec30c88207a544a73ae9#diff-3a25cbd6a20d326a71f8c8a946c62abd
https://github.com/mesa3d/mesa/commit/ccfcb9d818b40564001b3cf2516367526de26c1d#diff-3a25cbd6a20d326a71f8c8a946c62abd
You could try to pick up the git of early May, or you could point the mesa-19.1.4 tag.
