### ISSUE TITLE
[updated] dependency no longer exists

### ISSUE THREAD

**Issue by kenan1099** [Ps3itaTeam/ps4linux-video-drivers#8]
```
warning: cannot resolve "lib32-elfutils", a dependency of "lib32-mesa-git"
:: The following package cannot be upgraded due to unresolvable dependencies:
      lib32-mesa-git
```
when adding the repo to a clean arch install and following the instructions.

**Comment by Ps3itaTeam** [comment]
Try now, i've updated the drivers and remove lib32-elfutils from the dependencies

**Comment by kquote03** [comment]
> Try now, i've updated the drivers and remove lib32-elfutils from the dependencies

Thank you, I actually installed a dummy package and it worked but I will try again today with a clean install. (I'm attempting an HDD install)

**Comment by kquote03** [comment]
It seems that llvm is breaking stuff again:

```
warning: cannot resolve "llvm-libs=11.0.1", a dependency of "mesa-git"
warning: cannot resolve "llvm-libs=11.0.1", a dependency of "mesa-git"
warning: cannot resolve "mesa-git", a dependency of "lib32-mesa-git"
warning: cannot resolve "lib32-elfutils", a dependency of "lib32-mesa-git"
warning: cannot resolve "lib32-llvm-libs=11.0.1", a dependency of "lib32-mesa-git"
:: The following packages cannot be upgraded due to unresolvable dependencies:
      mesa-git  lib32-mesa-git

:: Do you want to skip the above packages for this upgrade? [y/N] 

```

**Comment by kquote03** [comment]
It also seems that the lib32-elfutils is still present

**Comment by kquote03** [comment]
Just tested installation again and seems to work without throwing errors, thanks!
